# Generated by Django 5.1 on 2024-08-12 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
