# Generated by Django 5.1 on 2024-08-12 03:30

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', usuarios.models.CustomUserManager()),
            ],
        ),
    ]
